spring.application.name: crypto-query
server.port: 2021

server:
    servlet-path: /api

management.endpoints.web.base.path: /
management:
    endpoint:
        health:
            show-details: always
management.endpoints.web.exposure.include: "*"

ticker.url.host: https://api.binance.com/api/v3/
ticker.url.endpoints:
    get-ticker-all: ticker/price
    get-ticker-by-currency: ticker/price?symbol=

user.email: fergrea82@gmail.com